### ISSUE TITLE
Corrigir erro de typo

### ISSUE THREAD

**Issue by AlexandreMagalhaesDosSantos** [AlexandreMagalhaesDosSantos/Motorcycles#1]
Existe um erro de typo na palavra e**z**emplo que deveria ser exemplo @JobsonAlmeida

**Comment by ghost** [comment]
Sim, eu vou corrigir

**Comment by ghost** [comment]
problema corrigido

**Comment by AlexandreMagalhaesDosSantos** [comment]
Estou reabrindo porque tem que ser tudo com letra maiúscula.

**Comment by ghost** [comment]
Pronto. Corrigido tudo para letra maiúscula.

**Comment by AlexandreMagalhaesDosSantos** [comment]
Agora tem que ser com letras maiúsculas e minúscula alternadas.

**Comment by MarcelaSantosTech** [comment]
> Agora tem que ser com letras maiúsculas e minúscula alternadas.

Eu acho que fica melhor com letras maiúsculas
